
services:
  postgres:
    image: postgres:16
    container_name: bi_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    container_name: bi_metabase
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:

    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase_app_db
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS=postgres
      - MB_DB_HOST=postgres

  data_importer:
    image: python:3.9-slim
    container_name: bi_data_importer
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=postgres
      - PYTHONUNBUFFERED=1
    command: tail -f /dev/null

